model_name=NN_cov

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/SIR/ \
  --model_id sir_iid \
  --model $model_name \
  --data SIR \
  --size_list 9000 \
  --steps 2 \
  --sigma 0.2 \
  --rho -0.5 \
  --beta 1 \
  --gamma 0.5 \
  --dt 0.01 \
  --target stage \
  --seq_len 1 \
  --pred_len 1 \
  --c_in 4 \
  --c_out 4 \
  --downsample 1 \
  --des 'Exp' \
  --d_model 64 \
  --batch_size 16 \
  --prints 100 \
  --learning_rate 0.001 \
  --patience 7 \
  --itr 1 \
  --train_epochs 15 \
  --inverse \
  --cov_bool \
  --jacobian \
  --jac_mean \
  --jac_mean_interval 20 \
  --jac_init 0 \
  --jac_end 9000 \
  --jac_interval 900 \
  --loss_lam 0.01